[package]
name = "csv_reading"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv-async = {version = "1", features = ["tokio"]}
tokio = {version = "1", features = ["full"]}
tokio-stream = "0.1"
