[package]
name = "clap_tutorial"
version = "0.1.0"
edition = "2021"
description = "hello clap"
authors = ["againxx"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3", features = ["derive"]}
